# Example defaults for springboot.command
DEFAULT_APP="localization-mgmt-service-api"
DEFAULT_POM="localization-mgmt-service-api/pom.xml"
DEFAULT_MAIN_CLASS="com.example.Application"
DEFAULT_PROJECT_RUN_SCRIPT="script/run-local-aws.sh"
DEFAULT_PROFILE="local-aws"
DEFAULT_REGION="us-east-2"
JVM_ARGS="-Dio.netty.transport.noNative=true"
# MVN_ARGS="-DskipTests"
