# Example defaults for snyk.command.sh
# please clone this file and remove the `.example` part from the name,
# and make sure you never commit it!!!
# (it is excluded from git by default already)
DEFAULT_SNYK_TOKEN="your_snyk_token"
DEFAULT_SNYK_ORG="b2253022-31af-4e04-bae8-9e06c518e3a9"
DEFAULT_SNYK_API_KEY_URL="https://app.snyk.io/account"
DEFAULT_SNYK_COMMAND="test"
DEFAULT_SNYK_TARGET_FILE=""
DEFAULT_SNYK_PROJECT_NAME=""
DEFAULT_SNYK_PROJECT_URL=""
DEFAULT_SNYK_OUTPUT_FORMAT="json"
DEFAULT_SNYK_INSTALL_CMD=""
DEFAULT_SNYK_ALLOW_FAILURE="0"
DEFAULT_SNYK_ARGS=""
DEFAULT_SNYK_MAVEN_ARGS=""
