# Example defaults for IDE setup commands
MAIN_CLASS="com.example.<service>.Application"
PROFILE="local-aws"
RUN_AWS_REGION="us-east-2"
DEVTOOLS_RESTART_ENABLED="false"
DEVTOOLS_RESTART_JVM_DISABLE="false"
